name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
jobs:
  test:
    with:
          ref: ${{ github.event.client_payload.sha }}
    uses: tryghost/actions/.github/workflows/test.yml@main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
